# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 725a8168cf5359a39c98375526a586e0955c69855fb59ed4ee6cd50a3c9b83eb831c11d1d142d7bb94022a7bb48e79982ead99e2d9dc0c34a2181d5eff12e201

test:
  secret_key_base: c324463da6713699e8ed5344394da794e053f1d226950c9ed599f591f29451187950e739de7038ae4077a0a4889dbbf2d6a3f903372d5156ded95e6d4db482e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
